// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waaxtcfkitdxhylxrvej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhYXh0Y2ZraXRkeGh5bHhydmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTQwNDcsImV4cCI6MjA3MjAzMDA0N30.4Vf0HzhoRb7-K75BAZpm9-fxv1pMQFhlEma2Kvrn4-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});